[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mongodb = "2"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
bcrypt = "0.11"
futures = "0.3"